// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: face_recognition_protos/embed.proto

package face_recognition_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_face_recognition_protos_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_protos_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_face_recognition_protos_embed_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_face_recognition_protos_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_recognition_protos_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_face_recognition_protos_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_face_recognition_protos_embed_proto protoreflect.FileDescriptor

const file_face_recognition_protos_embed_proto_rawDesc = "" +
	"\n" +
	"#face_recognition_protos/embed.proto\x12\x05embed\"$\n" +
	"\fImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"G\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2M\n" +
	"\fFaceEmbedder\x12=\n" +
	"\fGetEmbedding\x12\x13.embed.ImageRequest\x1a\x18.embed.EmbeddingResponseB$Z\"genprotos/face_recognition_serviceb\x06proto3"

var (
	file_face_recognition_protos_embed_proto_rawDescOnce sync.Once
	file_face_recognition_protos_embed_proto_rawDescData []byte
)

func file_face_recognition_protos_embed_proto_rawDescGZIP() []byte {
	file_face_recognition_protos_embed_proto_rawDescOnce.Do(func() {
		file_face_recognition_protos_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_face_recognition_protos_embed_proto_rawDesc), len(file_face_recognition_protos_embed_proto_rawDesc)))
	})
	return file_face_recognition_protos_embed_proto_rawDescData
}

var file_face_recognition_protos_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_face_recognition_protos_embed_proto_goTypes = []any{
	(*ImageRequest)(nil),      // 0: embed.ImageRequest
	(*EmbeddingResponse)(nil), // 1: embed.EmbeddingResponse
}
var file_face_recognition_protos_embed_proto_depIdxs = []int32{
	0, // 0: embed.FaceEmbedder.GetEmbedding:input_type -> embed.ImageRequest
	1, // 1: embed.FaceEmbedder.GetEmbedding:output_type -> embed.EmbeddingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_face_recognition_protos_embed_proto_init() }
func file_face_recognition_protos_embed_proto_init() {
	if File_face_recognition_protos_embed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_face_recognition_protos_embed_proto_rawDesc), len(file_face_recognition_protos_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_face_recognition_protos_embed_proto_goTypes,
		DependencyIndexes: file_face_recognition_protos_embed_proto_depIdxs,
		MessageInfos:      file_face_recognition_protos_embed_proto_msgTypes,
	}.Build()
	File_face_recognition_protos_embed_proto = out.File
	file_face_recognition_protos_embed_proto_goTypes = nil
	file_face_recognition_protos_embed_proto_depIdxs = nil
}
